development:
  adapter: postgresql
  encoding: utf8
  database: little_bits_development
  host: localhost
  # port: 5432
  username: chris
  password:
  pool: 5
  timeout: 10_000

test:
  adapter: postgresql
  host: localhost
  encoding: utf8
  database: little_bits_test
  username: chris
  password:
